import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ChevronRight,CheckCircle2,X,UtensilsCrossed,CalendarDays,Save,Trash2,LogOut,RefreshCw} from 'lucide-react';
import './styles.css';

const API=import.meta.env.VITE_NEON_DATA_API_URL||'https://ep-dark-poetry-b5z0bgxk.apirest.c-7.us-east-2.aws.neon.tech/neondb/rest/v1';
const FALLBACK_IMAGE='/menu-default.svg';
const CATS=['Tous','Plats','Spécialités','Boissons'];
const money=v=>new Intl.NumberFormat('fr-FR').format(Number(v)||0)+' FCFA';
const todayISO=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Abidjan'});
const imageFor=item=>item?.image_url||FALLBACK_IMAGE;
const sessionKey='cana_admin_session';
const getSession=()=>localStorage.getItem(sessionKey)||'';
async function api(action,payload={},session=getSession()){
 const res=await fetch(`${API}/rpc/cana_api`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({p_action:action,p_payload:payload,p_session:session||null})});
 let data=null;try{data=await res.json()}catch{}
 if(!res.ok){const msg=data?.message||data?.error||data?.hint||`Erreur serveur (${res.status})`;throw new Error(msg)}
 return Array.isArray(data)&&data.length===1?data[0]:data;
}
const b64ToBytes=v=>{const pad='='.repeat((4-v.length%4)%4),b=atob((v+pad).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...b].map(c=>c.charCodeAt(0)))};
async function registerPush(phone=''){
 try{
  if(!('serviceWorker' in navigator)||!('PushManager' in window)||!('Notification' in window))return;
  const keyData=await api('push_public_key',{}); const vapid=keyData?.public_key;if(!vapid)return;
  const permission=Notification.permission==='granted'?'granted':await Notification.requestPermission();if(permission!=='granted')return;
  const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();
  if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64ToBytes(vapid)});
  const json=sub.toJSON();
  await api('register_push',{phone:phone||null,endpoint:sub.endpoint,p256dh:json.keys?.p256dh||'',auth:json.keys?.auth||''});
 }catch{}
}
function SafeImage({src,alt,className='',fallback=FALLBACK_IMAGE}){const [failed,setFailed]=useState(false);return <img className={className} src={failed?fallback:src||fallback} alt={alt||''} onError={()=>setFailed(true)} loading="lazy"/>}

function ClientApp(){
 const [items,setItems]=useState([]),[category,setCategory]=useState('Tous'),[selected,setSelected]=useState(null),[reservationOpen,setReservationOpen]=useState(false),[customOpen,setCustomOpen]=useState(false),[lookup,setLookup]=useState(false),[phone,setPhone]=useState(''),[history,setHistory]=useState(null),[status,setStatus]=useState('');
 useEffect(()=>{loadMenu()},[]);
 async function loadMenu(){try{const data=await api('public_menu');if(Array.isArray(data))setItems(data.map(x=>({...x,category:x.category||'Plats'})))}catch(e){setStatus(e.message)}}
 function openReservation(dish=null){setStatus('');setSelected(dish);setReservationOpen(true)}
 async function reserve(e){e.preventDefault();setStatus('');const fd=new FormData(e.currentTarget);const p={full_name:fd.get('full_name'),phone:fd.get('phone'),reservation_date:fd.get('date'),reservation_time:fd.get('time')||'12:00',dish_count:Number(fd.get('dish_count')),notes:fd.get('notes'),dish_id:fd.get('dish_id')||null};try{await api('public_reserve',p);setStatus('success');e.currentTarget.reset();registerPush(p.phone)}catch(err){setStatus(err.message)}}
 async function customRequest(e){e.preventDefault();setStatus('');const fd=new FormData(e.currentTarget);const p={full_name:fd.get('full_name'),phone:fd.get('phone'),request_text:fd.get('request_text')};try{await api('custom_request',p);setStatus('success');e.currentTarget.reset();registerPush(p.phone)}catch(err){setStatus(err.message)}}
 async function find(e){e.preventDefault();setStatus('');try{setHistory(await api('my_reservations',{phone}))}catch(err){setStatus(err.message)}}
 async function cancel(id){try{await api('cancel_reservation',{id,phone});setHistory(await api('my_reservations',{phone}))}catch(err){setStatus(err.message)}}
 const visible=category==='Tous'?items:items.filter(x=>(x.category||'Plats')===category);
 return <div className="site">
  <header className="site-header"><a className="brand" href="#accueil" aria-label="Les Délices de CANA"><SafeImage src="/brand/cana-logo.png" alt="Les Délices de CANA" fallback="/brand/cana-logo.png"/></a><nav><button onClick={()=>{setHistory(null);setStatus('');setLookup(true)}}>Mes réservations</button></nav></header>
  <main>
   <section id="accueil" className="hero"><div className="hero-content"><span className="kicker">Les Délices de CANA · Gonaté</span><h1><span>Ici, la cuisine a le</span><span>goût de chez vous.</span></h1><p>Découvrez le menu du jour et les saveurs de CANA, préparés avec soin pour régaler votre journée et éveiller vos papilles.</p></div></section>
   <section id="menu" className="catalog"><div className="catalog-head"><div><span className="kicker">LE MENU DU JOUR</span><h2>Réserver votre plat préféré à l'avance.</h2></div><span className="open"><i/> Ouvert</span></div><div className="category-bar">{CATS.map(c=><button className={category===c?'active':''} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="catalog-grid">{visible.map(item=><article className="product" key={item.id} onClick={()=>setSelected(item)}><div className="product-image"><SafeImage src={imageFor(item)} alt={item.name}/><span>{money(item.price)}</span></div><div className="product-info"><small>{item.category||'Plats'}</small><h3>{item.name}</h3><p>{item.description}</p><button onClick={e=>{e.stopPropagation();setSelected(item)}}>Voir le plat <ChevronRight size={15}/></button></div></article>)}</div>{!visible.length&&<div className="empty-state">Le menu du jour sera publié ici.</div>}</section>
   <section className="quick-actions"><div><span className="kicker">SUR DEMANDE</span><h2>Vous voulez un plat particulier</h2><p>Décrivez ce que vous souhaitez préparer à l'avance et notre équipe vous répondra.</p></div><div className="quick-actions-buttons"><button className="btn dark" onClick={()=>{setStatus('');setCustomOpen(true)}}>Commander à l'avance ici <ChevronRight size={17}/></button></div></section>
  </main>
  <footer><SafeImage src="/brand/cana-logo.png" alt="Les Délices de CANA"/><span>© {new Date().getFullYear()} Les Délices de CANA · Gonaté</span><a href="#accueil">Retour en haut</a></footer>
  {selected&&!reservationOpen&&<div className="overlay" onClick={()=>setSelected(null)}><div className="product-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X/></button><div className="modal-image"><SafeImage src={imageFor(selected)} alt={selected.name}/></div><span className="kicker">{selected.category||'Plats'}</span><h2>{selected.name}</h2><p>{selected.description}</p><strong>{money(selected.price)}</strong><button className="btn dark full" onClick={()=>openReservation(selected)}>Réserver ce plat</button></div></div>}
  {reservationOpen&&<div className="overlay" onClick={()=>{setReservationOpen(false);setStatus('')}}><div className="booking-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>{setReservationOpen(false);setStatus('')}}><X/></button><span className="kicker">Réservation</span><h2>Réserver</h2>{status==='success'?<div className="reservation-success"><CheckCircle2 size={42}/><h3>Demande enregistrée</h3><p>Votre demande de réservation a bien été transmise au restaurant.</p><button className="btn dark full" onClick={()=>{setReservationOpen(false);setStatus('')}}>Fermer</button></div>:<form className="booking-form" onSubmit={reserve}><label>Nom complet<input name="full_name" required placeholder="Votre nom et prénom"/></label><label>Téléphone<input name="phone" required inputMode="tel" placeholder="07 00 00 00 00"/></label><div className="form-two"><label>Jour<input name="date" type="date" required defaultValue={todayISO()}/></label><label>Heure souhaitée<input name="time" type="time" required/></label></div><label>Plat souhaité<select name="dish_id" defaultValue={selected?.dish_id||selected?.id||''}><option value="">Choisir un plat</option>{items.map(item=><option key={item.id} value={item.dish_id||item.id}>{item.name} — {money(item.price)}</option>)}</select></label><label>Nombre de plats<select name="dish_count" defaultValue="1">{[1,2,3,4,5,6,7,8,9,10].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label>Précision (facultatif)<textarea name="notes" rows="3" maxLength="350" placeholder="Une précision pour l’équipe..."/></label><button className="btn dark full">Confirmer ma réservation</button>{status&&status!=='success'&&<small className="error">{status}</small>}</form>}</div></div>}
  {customOpen&&<div className="overlay" onClick={()=>{setCustomOpen(false);setStatus('')}}><div className="booking-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>{setCustomOpen(false);setStatus('')}}><X/></button><span className="kicker">Commande à l'avance</span><h2>Vous voulez un plat particulier</h2>{status==='success'?<div className="reservation-success"><CheckCircle2 size={42}/><h3>Demande envoyée</h3><p>Votre demande a bien été transmise à l'équipe.</p><button className="btn dark full" onClick={()=>{setCustomOpen(false);setStatus('')}}>Fermer</button></div>:<form className="booking-form" onSubmit={customRequest}><label>Nom et prénom<input name="full_name" required maxLength="120" placeholder="Votre nom et prénom"/></label><label>Contact<input name="phone" required inputMode="tel" maxLength="30" placeholder="Votre numéro de téléphone"/></label><label>Votre demande<textarea name="request_text" rows="6" required maxLength="350" placeholder="Décrivez le plat ou la préparation souhaitée (350 caractères maximum)."/></label><small className="field-hint">350 caractères maximum.</small><button className="btn dark full">Valider ma demande</button>{status&&status!=='success'&&<small className="error">{status}</small>}</form>}</div></div>}
  {lookup&&<div className="overlay" onClick={()=>setLookup(false)}><div className="lookup" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setLookup(false)}><X/></button><span className="kicker">Espace client</span><h2>Ma réservation</h2>{!history?<form onSubmit={find}><p>Entrez le numéro utilisé lors de la réservation.</p><label>Téléphone<input value={phone} onChange={e=>setPhone(e.target.value)} required inputMode="tel"/></label><button className="btn dark full">Rechercher</button>{status&&<small className="error">{status}</small>}</form>:<div className="history">{history.length?history.map(r=><div className="history-item" key={r.id}><div><b>{r.dish_name||'Commande particulière'}</b>{r.notes&&<span>{r.notes}</span>}<span>{r.reservation_date} · {String(r.reservation_time).slice(0,5)} · {r.dish_count} plat{r.dish_count>1?'s':''}</span><em className={'badge '+r.status}>{r.status}</em></div>{['pending','confirmed'].includes(r.status)&&<button className="cancel" onClick={()=>cancel(r.id)}>Annuler</button>}</div>):<p>Aucune réservation trouvée pour ce numéro.</p>}{status&&<small className="error">{status}</small>}</div>}</div></div>}
 </div>
}

function AdminApp(){
 const [session,setSession]=useState(getSession()),[admin,setAdmin]=useState(null),[tab,setTab]=useState('reservations'),[reservations,setReservations]=useState([]),[menus,setMenus]=useState([]),[dishes,setDishes]=useState([]),[message,setMessage]=useState(''),[menuForm,setMenuForm]=useState({date:todayISO(),time:'06:00',title:'Menu du jour'}),[dish,setDish]=useState({name:'',description:'',price:'',category:'Plats',image_url:''}),[editing,setEditing]=useState(null),[login,setLogin]=useState({phone:'',password:''});
 useEffect(()=>{if(!session)return;api('admin_me',{},session).then(r=>{if(r?.authenticated){setAdmin(r.admin);refresh()}else{localStorage.removeItem(sessionKey);setSession('')}}).catch(()=>{localStorage.removeItem(sessionKey);setSession('')})},[session]);
 async function signIn(e){e.preventDefault();setMessage('');try{const r=await api('admin_login',{phone:login.phone,password:login.password},'');localStorage.setItem(sessionKey,r.token);setSession(r.token);setAdmin(r.admin);registerPush()}catch(err){setMessage(err.message)}}
 async function call(action,payload){try{return await api(action,payload,session)}catch(err){setMessage(err.message);throw err}}
 async function refresh(){try{const r=await call('admin_dashboard',{});setReservations(r.reservations||[]);setMenus(r.menus||[]);setDishes(r.dishes||[])}catch{}}
 async function updateReservation(id,status){await call('admin_update_reservation',{id,status});setMessage(status==='confirmed'?'Réservation validée.':'Réservation terminée.');refresh()}
 async function deleteReservation(id){if(!confirm('Supprimer cette réservation ?'))return;await call('admin_delete_reservation',{id});setMessage('Réservation supprimée.');refresh()}
 async function saveDish(e){e.preventDefault();await call('admin_save_dish',{...dish,price:Number(dish.price),active:true,id:editing||null});setMessage('Plat enregistré.');setDish({name:'',description:'',price:'',category:'Plats',image_url:''});setEditing(null);refresh()}
 async function deleteDish(id){if(!confirm('Supprimer ce plat ?'))return;await call('admin_delete_dish',{id});setMessage('Plat supprimé.');refresh()}
 async function createMenu(e){e.preventDefault();const publishAt=new Date(`${menuForm.date}T${menuForm.time}:00`).toISOString();await call('admin_save_menu',{service_date:menuForm.date,publish_at:publishAt,status:'scheduled',title:menuForm.title||'Menu du jour'});setMessage('Menu programmé.');refresh()}
 async function deleteMenu(id){if(!confirm('Supprimer ce menu ?'))return;await call('admin_delete_menu',{id});setMessage('Menu supprimé.');refresh()}
 async function addDish(menuId,dishId){await call('admin_add_menu_item',{menu_id:menuId,dish_id:dishId});refresh()}
 async function removeItem(id){await call('admin_remove_menu_item',{id});refresh()}
 async function logout(){try{await call('admin_logout',{})}catch{}localStorage.removeItem(sessionKey);setSession('');setAdmin(null)}
 if(!session||!admin)return <div className="admin-login"><SafeImage src="/brand/cana-logo.png" alt="Les Délices de CANA"/><span className="kicker">Espace privé</span><h1>Connexion</h1><form onSubmit={signIn}><label>Numéro de téléphone<input type="tel" inputMode="tel" value={login.phone} onChange={e=>setLogin({...login,phone:e.target.value})} placeholder="07 00 00 00 00" required/></label><label>Mot de passe<input type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} required/></label><button className="btn dark full">Se connecter</button>{message&&<small className="error">{message}</small>}</form></div>;
 return <div className="admin"><aside><SafeImage src="/brand/cana-logo.png" alt="Les Délices de CANA"/><button className={tab==='reservations'?'active':''} onClick={()=>setTab('reservations')}>Réservations</button><button className={tab==='menus'?'active':''} onClick={()=>setTab('menus')}>Menus</button><button className={tab==='dishes'?'active':''} onClick={()=>setTab('dishes')}>Plats & images</button><button onClick={()=>refresh()}><RefreshCw size={16}/> Actualiser</button><button className="logout" onClick={logout}><LogOut size={16}/> Déconnexion</button></aside><section className="admin-main"><div className="admin-top"><div><span className="kicker">Les Délices de CANA</span><h1>Administration</h1></div><span className="admin-status">Connecté · {admin.full_name}</span></div>{message&&<div className="notice">{message}</div>}
 {tab==='reservations'&&<div className="admin-card"><div className="card-head"><h2>Réservations</h2><span>{reservations.length} demande(s)</span></div><div className="table-scroll"><table><thead><tr><th>Client</th><th>Date</th><th>Heure</th><th>Plats</th><th>Plat</th><th>Demande</th><th>Statut</th></tr></thead><tbody>{reservations.map(r=><tr key={r.id}><td><b>{r.customer_name}</b><small>{r.customer_phone}</small></td><td>{r.reservation_date}</td><td>{String(r.reservation_time).slice(0,5)}</td><td>{r.dish_count}</td><td><div className="admin-request-text">{r.dish_name||'Commande particulière'}{r.notes&&<small>{r.notes}</small>}</div></td><td><div className="admin-reservation-actions"><span className={'badge '+r.status}>{r.status}</span>{r.status==='pending'&&<button className="mini-btn" onClick={()=>updateReservation(r.id,'confirmed')}>Valider</button>}{r.status==='confirmed'&&<button className="mini-btn" onClick={()=>updateReservation(r.id,'completed')}>Terminer</button>}{r.status!=='completed'&&<button className="mini-btn danger" onClick={()=>deleteReservation(r.id)}>Supprimer</button>}</div></td></tr>)}</tbody></table></div></div>}
 {tab==='menus'&&<div className="admin-stack"><div className="admin-card"><h2>Programmer le menu</h2><form className="inline-form" onSubmit={createMenu}><label>Date<input type="date" value={menuForm.date} onChange={e=>setMenuForm({...menuForm,date:e.target.value})}/></label><label>Heure de publication<input type="time" value={menuForm.time} onChange={e=>setMenuForm({...menuForm,time:e.target.value})}/></label><label>Titre<input value={menuForm.title} onChange={e=>setMenuForm({...menuForm,title:e.target.value})}/></label><button className="btn dark"><CalendarDays size={16}/> Programmer</button></form></div>{menus.map(m=><div className="admin-card" key={m.id}><div className="card-head"><div><h2>{m.title||'Menu du jour'}</h2><span>{m.service_date} · {new Date(m.publish_at).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</span></div><span className={'badge '+m.status}>{m.status}</span><button className="mini-btn danger" onClick={()=>deleteMenu(m.id)}>Supprimer</button></div><div className="menu-items">{(m.menu_items||[]).map(mi=><div className="menu-row" key={mi.id}><span>{mi.name} · {money(mi.price)}</span><button onClick={()=>removeItem(mi.id)}><Trash2 size={15}/></button></div>)}</div><select className="add-select" onChange={e=>{if(e.target.value)addDish(m.id,e.target.value);e.target.value=''}}><option value="">＋ Ajouter un plat à ce menu</option>{dishes.filter(d=>d.active).map(d=><option key={d.id} value={d.id}>{d.name} — {money(d.price)}</option>)}</select></div>)}</div>}
 {tab==='dishes'&&<div className="admin-stack"><div className="admin-card"><div className="card-head"><h2>{editing?'Modifier le plat':'Ajouter un plat'}</h2>{editing&&<button className="text-btn" onClick={()=>{setEditing(null);setDish({name:'',description:'',price:'',category:'Plats',image_url:''})}}>Annuler</button>}</div><form onSubmit={saveDish}><label>Nom<input required value={dish.name} onChange={e=>setDish({...dish,name:e.target.value})}/></label><label>Description<textarea value={dish.description} onChange={e=>setDish({...dish,description:e.target.value})}/></label><div className="form-two"><label>Prix<input required type="number" min="0" value={dish.price} onChange={e=>setDish({...dish,price:e.target.value})}/></label><label>Catégorie<select value={dish.category} onChange={e=>setDish({...dish,category:e.target.value})}><option>Plats</option><option>Spécialités</option><option>Boissons</option></select></label></div><label>URL de l'image<input type="url" value={dish.image_url} onChange={e=>setDish({...dish,image_url:e.target.value})} placeholder="https://..."/></label>{dish.image_url&&<SafeImage className="preview" src={dish.image_url} alt="Aperçu"/>}<button className="btn dark"><Save size={16}/> Enregistrer le plat</button></form></div><div className="admin-card"><div className="card-head"><h2>Catalogue</h2><span>{dishes.length} plat(s)</span></div><div className="dish-list">{dishes.map(d=><div className="dish-admin-row" key={d.id}><div className="thumb">{d.image_url?<SafeImage src={d.image_url} alt=""/>:<UtensilsCrossed size={20}/>}</div><div className="dish-admin-copy"><b>{d.name}</b><span>{d.category} · {money(d.price)}</span></div><button onClick={()=>{setEditing(d.id);setDish({name:d.name,description:d.description||'',price:d.price,category:d.category||'Plats',image_url:d.image_url||''})}}><Save size={16}/></button><button onClick={()=>deleteDish(d.id)}><Trash2 size={16}/></button></div>)}</div></div></div>}
 </section></div>
}
createRoot(document.getElementById('root')).render(location.pathname==='/me'?<AdminApp/>:<ClientApp/>);